name: housing
version: '1.0.0'
config-version: 2

profile: housing

model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analyses"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  housing:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
